### ISSUE TITLE
Publishing your theme

### ISSUE THREAD

**Issue by jimmyff** [mr-karan/website#5]
Hi, really nice blog. I see your theme is based on hugo-ink and you've done a really nice job with making it work nicely with Zola. I noticed in your todo list that you are planning to publish it at some point, I was just wondering if you have this scheduled for any time soon? Don't worry if not!

Thanks

**Comment by mr-karan** [comment]
Hey. Unfortunately, never got the time for it and don't really have any deadline for it. I'll keep this issue open though.

**Comment by jimmyff** [comment]
Not a problem.

Would you have any issue if I were to create a theme repo based off this? It would of course include credit & links back to your github profile & repo as well as the hugo-ink project. I would like to use the theme for my site and I would like to seperate the theme from the content. If this is okay then would you be okay with it being published under the default Zola theme licence: MIT?

Thanks

**Comment by mr-karan** [comment]
Yep, that's perfectly alright :)

**Comment by jimmyff** [comment]
Great thanks, I'll pop the repo link here for you to see once I've got something together.

**Comment by jimmyff** [comment]
Hey @mr-karan, I've pushed the theme repo: https://github.com/jimmyff/zola-inky -Let me know what you think and if you want any alterations making?

I'll be adding more to it as time goes on but figured this was enough to start with.

**Comment by mr-karan** [comment]
@jimmyff Excellent stuff! The theme looks really good :)

**Comment by jimmyff** [comment]
Great, glad you approve! I'll close this issue now but feel free to let me know if you want anything adding or updating theme wise
